# docker-compose.yml for running a local copy of the declprofs Web app

services:

  db:
    image: mariadb:10.9.4
    environment:
      - MYSQL_DATABASE=declprofs
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      # DECLPROFS_DB_PORT is set in .env
      - ${DECLPROFS_DB_PORT}:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./seed:/docker-entrypoint-initdb.d
      - ./seed/202406-001-schema.sql:/docker-entrypoint-initdb.d/202406-001-schema.sql

  httpd:
    build: .
    image: declprofs
    volumes:
      # Like production:
      - ./devsupport/access_params:/usr/local/etc/access_params
      - ./devsupport/dbs.conf:/usr/local/etc/dbs.conf
      # Not like production — Mount source code on top of the
      # `docker build`t code, for faster embugging:
      - ./cgi-bin:/usr/local/apache2/cgi-bin:ro
      - .:/usr/local/apache2/htdocs/extra:ro
      - ./images:/usr/local/apache2/htdocs/images:ro
      - ./tmpl:/app/tmpl:ro
    environment:
      - REDIRECT_URI=${REDIRECT_URI}
      - OIDC_METADATA_URL=https://login.microsoftonline.com/f6c2556a-c4fb-4ab1-a2c7-9e220df11c43/v2.0/.well-known/openid-configuration
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_CRYPTO_PASS=0123456789abcdef0123456789abcdef
    links:
      - db:db
    ports:
      # DECLPROFS_HTTP_PORT is set in .env
      - "${DECLPROFS_HTTP_PORT}:8080"

volumes:
  mariadb:
