# docker-compose.yml for running a local copy of the declprofs Web app

services:

  db:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      # DECLPROFS_DB_PORT is set in .env
      - ${DECLPROFS_DB_PORT}:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./seed/202406-001-schema.sql:/docker-entrypoint-initdb.d/202406-001-schema.sql

  httpd:
    build: .
    image: declprofs
    volumes:
      # Like production:
      - ./devsupport/access_params:/app/etc/access_params
      - ./devsupport/dbs.conf:/usr/local/etc/dbs.conf
      # Not like production — Mount source code on top of the
      # `docker build`t code, for faster embugging:
      - ./cgi-bin:/usr/local/apache2/cgi-bin:ro
      - .:/usr/local/apache2/htdocs/extra:ro
      - ./images:/usr/local/apache2/htdocs/images:ro
      - ./tmpl:/app/tmpl:ro
    links:
      - db:db
    ports:
      # DECLPROFS_HTTP_PORT is set in .env
      - "${DECLPROFS_HTTP_PORT}:8080"

volumes:
  mariadb:
