- tags: always
  include_vars: declprofs-vars.yml

- name: "Declprofs image"
  when: inventory_environment == "test"
  include_tasks:
    file: declprofs-image.yml
    apply:
      tags:
      - declprofs
      - declprofs.image
  tags:
  - declprofs
  - declprofs.image

- name: "Declprofs container"
  include_tasks:
    file: declprofs-container.yml
    apply:
      tags:
      - declprofs
      - declprofs.container
  tags:
  - declprofs
  - declprofs.container
