- tags: always
  include_vars: versions.yml

- name: "Install software"
  include_tasks:
    file: vm-software.yml
    apply:
      tags:
      - vm
      - vm.software
  tags:
  - vm
  - vm.software

- include_role:
    name: epfl_si.traefik.traefik
    apply:
      tags:
      - vm.traefik
  vars:
    traefik_root_location: /srv/traefik
    traefik_container_platform: podman
    traefik_podman_image: "docker.io/library/traefik:v{{ traefik_version }}"
  tags:
  - vm.traefik
