CREATE DATABASE IF NOT EXISTS `accred` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE DATABASE IF NOT EXISTS `cadi` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE DATABASE IF NOT EXISTS `dinfo` /*!40100 DEFAULT CHARACTER SET latin1 */;