containers:
  "hosts":  # Scarequotes intended - Ansible wants to believe these
            # are distinct "hosts", even though they are actually
            # distinct containers (on the same host; see
            # also containers: → vars: in inventory-prod.yml)
    declprofs-test:
      inventory_deployment_stage: test
      inventory_local_port: 8087
      inventory_web_hostname: declprofs-test.epfl.ch
      ansible_host: itsxact0002.xaas.epfl.ch
