- name: "No firewalls, no SELinux"
  hosts: vms
  gather_facts: no
  tasks:
  - tags: [ vm, vm.security ]
    ansible.posix.selinux:
      state: disabled
  - tags: [ vm, vm.security ]
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false

- name: "General VM configuration"
  hosts: vms
  gather_facts: no
  roles:
  - roles/declprofs-vm

- name: "declprofs containerized application"
  hosts: containers
  gather_facts: no
  roles:
  - roles/declprofs-app
