- name: "No firewalls, no SELinux"
  hosts: vms
  gather_facts: no
  tasks:
  - tags: [ vm, vm.security ]
    ansible.posix.selinux:
      state: disabled
  - tags: [ vm, vm.security ]
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false

- name: "Deploy software"
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: "Deploy cgi-bin"
      copy:
        src: ../cgi-bin
        dest: /var/www/vhosts/declprofs.epfl.ch/cgi-bin/
